# arXiv Agent 配置文件
arxiv:
  # 监控的arXiv分类，可以设置多个
  categories:
    - "cs.AI"      # 人工智能
    - "cs.LG"      # 机器学习
    - "cs.RO"      # 机器人
    - "cs.CV"      # 计算机视觉
  
  # 关键词过滤
  keywords:
    - "Vision Language Action "
    - "vla"
    - "Vision-Language-Action"
    - "Multivariate Time Series Forecasting"
    - "spatio-temporal prediction"
    - "traffic prediction"
  
  # 每日抓取论文数量限制
  max_papers_per_day: 20

# 大模型API配置
ai_model:
  # 支持的模型: openai, anthropic, custom
  provider: "deepseek"
  
  # OpenAI配置
  deepseek:
    model: "deepseek-chat"
    api_key_env: "DEEPSEEK_API_KEY"
    base_url: "https://api.deepseek.com"
  
  # 分析提示词
  analysis_prompt: |
    [System Role]  
    你是一位熟悉顶级机器学习/人工智能会议（如 AAAI/NeurIPS/ICLR）风格的资深论文总结者。  
    请生成一份纯文本、结构清晰的论文总结。

    [关键约束]  
    1. **必须严格使用以下七个标题，且顺序不可更改**（不得增减或替换）：  
    - 论文概要  
    - 研究动机  
    - 核心贡献与创新点  
    - 方法概述  
    - 改进建议和未来研究方向 

  
    1. **以证据为先**：每一项陈述都必须有来自论文的明确依据（如章节、图表、公式、页码）。若无直接证据，请明确写明：“论文中未找到直接证据。”  
    2. 语气应中立、客观、信息明确。  
    3. 避免推测性内容；除非出现在论文参考文献中，否则不得引用外部资料。

    [输入]  
    - 完整的学术研究论文。

    [输出模板]  
    请严格按照以下七个部分撰写总结：

    1. **论文概要**  
    - 用简洁中立的语言概述论文所解决的问题、提出的方法、主要发现和研究范围（不超过150字）。  
    - 避免使用评价性语言或预测性表述。

    2. **研究动机**  
    - 说明论文试图解决的科学或实际问题缺口。  
    - 指出作者认为现有工作存在哪些不足，从而引出本研究（需引用论文中的具体章节或参考文献）。  
    - 若动机未明确陈述但可合理推断，请注明：“动机由上下文推断；论文中未明确说明。”

    3. **核心贡献与创新点**  
    - 列出并描述论文提出的新颖内容（如新算法、理论见解、数据集、架构等）。  
    - 对每项贡献，提供具体依据（如“见第3.1节；公式(2)；图2”），并说明其与论文所引前人工作的区别或拓展之处。  
    - 注意区分实现细节与概念性创新。

    4. **方法概述**  
    - 概述技术方案：包括模型设计、训练流程、理论框架或实验设置。  
    - 引用关键公式、算法或结构组件（如“算法1；第3.2节；公式(3)”）。  
    - 说明所用评估指标、数据集及对比基线，并引用相关表格或章节（如“表1；第4节”）。

    5. **改进建议和未来研究方向** 
    - 指出作者明确承认或从方法/结果中可推断出的限制（如可扩展性、假设过强、数据偏差等）并评估未提及的潜在局限性。 
    - 根据文章的研究方法、实验评估等总结有哪些论文还有哪些改进建议 
    - 提出从该论文出发结合多个领域知识的的改进点，并评估可行性  

    [风格与篇幅]  
    - 语气：客观、准确、信息导向。  
    - 强调可追溯性：所有陈述必须能从原文验证。  

# 输出配置
output:
  # 输出目录
  output_dir: "papers"
  
  # 文件命名格式
  filename_format: "{date}_papers.md"
  
  # 日期格式
  date_format: "%Y-%m-%d"

# GitHub配置
github:
  # 仓库信息
  repo_owner: "Xxyuli"
  repo_name: "arxiv-daily"
  
  # 分支
  branch: "master"

